/* SIMB: estoque, ACAPS, recebimento e relatórios. Dados locais de demonstração. */
const MATERIAL_GROUPS=['Munição letal','Munição não letal','Granada','Spray','Recarga / cartucho','Material de treinamento','Outros consumíveis'];
const demoMaterials=[
 ['9×19 mm','Munição letal','9×19 mm','',1000,2.5],
 ['5,56×45 mm','Munição letal','5,56×45 mm','',500,5],
 ['Calibre 12 — letal','Munição letal','12','',200,6],
 ['AM-403 — monoimpacto','Munição não letal','12','am-403',100,28],
 ['AM-403/A — impacto triplo','Munição não letal','12','am-403a',100,30],
 ['GL-305 — lacrimogênea CS','Granada','','gl-305',20,0],
 ['GL-307 — luz e som','Granada','','gl-307',20,0],
 ['GL-308 — pimenta OC','Granada','','gl-308',20,0],
 ['GL-108 Advantage MINI — pimenta','Spray','','gl-108-advantage-mini',20,0],
 ['GL-108/E MED — espuma','Spray','','gl-108e-med',20,0],
 ['GL-108/CS MAX — lacrimogêneo','Spray','','gl-108cs-max',10,0],
 ['Recarga de treinamento — cadastrar modelo','Material de treinamento','','',30,0]
].map(([name,group,caliber,slug,balance,unitCost],i)=>({id:`MAT-DEMO-${i+1}`,name,group,caliber,manufacturer:slug?'Condor':'Fictício',model:name.split(' — ')[0],unit:group==='Spray'?'Frasco':'Unidade',lot:'LOTE-FICTICIO',expiry:'',balance,partial:0,quarantine:0,unitCost,demo:true,source:slug?`https://www.condornaoletal.com.br/product/${slug}`:''}));
let materialQuery='',reportFilters={type:'stock',from:'',to:'',query:''},invoiceDraft=null;
function ensureModules(){state.materials??=structuredClone(demoMaterials);state.acaps??=[];state.invoices??=[];state.movements??=[];state.schemaVersion=2;}
ensureModules();
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'});
const stamp=()=>new Date().toISOString();
const uid=p=>`${p}-${crypto.randomUUID()}`;
const options=(values,current='')=>values.map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('');
const materialById=id=>state.materials.find(m=>m.id===id);
function need(condition,message){if(!condition)throw new Error(message);}
function amount(value,label,positive=false){const n=Number(value);need(Number.isSafeInteger(n)&&n>=(positive?1:0),`${label}: informe uma quantidade inteira ${positive?'maior que zero':'não negativa'}.`);return n;}
function mutate(work){const before=structuredClone(state);try{work();saveState();return true;}catch(error){state=before;showToast(error.message||'Não foi possível salvar.');return false;}}
function movement(type,m,quantity,reference,note=''){state.movements.push({id:uid('MOV'),date:stamp(),type,materialId:m.id,name:m.name,group:m.group,lot:m.lot,quantity,unit:m.unit,reference,note,actor:'MARCELO SEIXAS'});}
function download(name,content,type='text/plain;charset=utf-8'){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function heading(title,subtitle,buttons=''){return `<div class="page-head"><div><p class="eyebrow">SIMB · PPSC</p><h1>${title}</h1><p>${subtitle}</p></div><div class="button-group">${buttons}</div></div>`;}
function table(headers,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Nenhum registro encontrado.</div>'}</div>`;}
function materialRows(list){return list.map(m=>[`${esc(m.name)}${m.source?` <a href="${esc(m.source)}" target="_blank" rel="noopener">Catálogo</a>`:''}`,esc(m.group),esc(m.caliber||'—'),esc(m.lot),m.expiry?formatDate(m.expiry):'Não informada',`${m.balance} ${esc(m.unit)}`,m.partial||0,m.quarantine||0,money(m.unitCost)]);}
views.materials=()=>heading('Estoque de consumíveis','Quantidades por material e lote. Estoque inicial e valores de teste são fictícios.','<button class="btn primary" id="newMaterial">＋ Registrar entrada</button>')+`<section class="panel"><label class="search"><input id="materialSearch" placeholder="Material, categoria, calibre ou lote" value="${esc(materialQuery)}"></label>${table(['Material','Categoria','Calibre','Lote','Validade','Disponível intacto','Uso parcial','Segregado','Valor unitário'],materialRows(state.materials.filter(m=>[m.name,m.group,m.caliber,m.lot].join(' ').toLowerCase().includes(materialQuery.toLowerCase()))))}</section>`;
views.acaps=()=>heading('ACAPS','Entregas, consumo e devoluções por atividade da academia.','<button class="btn primary" id="newAcaps">＋ Nova atividade</button>')+`<section class="panel">${table(['Registro / atividade','Data','Curso / turma','Responsável','Situação',''],state.acaps.map(a=>[`${esc(a.id)}<br><b>${esc(a.activity)}</b>`,formatDate(a.date),`${esc(a.course)} / ${esc(a.className)}`,esc(a.officer.nome),`<span class="status ${a.status==='Aberta'?'loaned':'available'}">${esc(a.status)}</span>`,`<button class="row-btn" data-acaps="${esc(a.id)}">${a.status==='Aberta'?'Conferir entrega':'Ver comprovante'}</button>`]))}</section>`;
views.invoices=()=>heading('Notas fiscais','Importe o XML da NF-e e confira os itens antes de incluir no estoque.','<button class="btn primary" id="openInvoice">＋ Receber nota fiscal</button>')+`<section class="panel"><p class="unit-note">Nesta fase: leitura automática de XML. PDF e imagem podem ser consultados na conferência manual; extração automática por OCR será uma próxima etapa.</p>${table(['NF / série','Emissão','Fornecedor','Chave','Itens','Entrada'],state.invoices.map(n=>[`${esc(n.number)} / ${esc(n.series)}`,formatDate(n.date),esc(n.supplier),esc(n.key),n.items.length,formatDate(n.created)]))}</section>`;
function reportData(){let {type,from,to,query}=reportFilters;let matches=(date,text)=>{const day=String(date||'').includes('T')?new Date(date).toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'}):String(date||'').slice(0,10);return (!from||day>=from)&&(!to||day<=to)&&(!query||text.toLowerCase().includes(query.toLowerCase()));};
 if(type==='stock')return {title:'Estoque de consumíveis',headers:['Material','Categoria','Calibre','Lote','Validade','Unidade','Disponível intacto','Uso parcial','Segregado','Valor unitário'],rows:state.materials.filter(m=>matches('',[m.name,m.group,m.caliber,m.lot].join(' '))).map(m=>[m.name,m.group,m.caliber,m.lot,m.expiry||'Não informada',m.unit,m.balance,m.partial,m.quarantine,money(m.unitCost)])};
 if(type==='equipment')return {title:'Acervo de armas e equipamentos',headers:['Patrimônio','Categoria','Fabricante','Modelo','Calibre','Série','Situação'],rows:state.equipment.filter(e=>matches('',Object.values(e).join(' '))).map(e=>[e.patrimonio,e.categoria,e.fabricante,e.modelo,e.calibre,e.serie,e.status])};
 if(type==='loans')return {title:'Cautelas de policiais penais',headers:['Cautela','Emissão','Matrícula','Policial penal','Tipo','Finalidade','Situação','Itens pendentes'],rows:state.loans.filter(l=>matches(l.created,[l.id,l.officerSnapshot.nome,l.matricula,l.purpose].join(' '))).map(l=>[l.id,formatDate(l.created),l.matricula,l.officerSnapshot.nome,l.type,l.purpose,l.status,l.items.filter(i=>!i.returned).map(i=>i.patrimonio).join(', ')])};
 if(type==='invoices')return {title:'Entradas por nota fiscal',headers:['Número','Série','Emissão','Fornecedor','Chave','Itens','Conferido por'],rows:state.invoices.filter(n=>matches(n.date,[n.number,n.supplier,n.key].join(' '))).map(n=>[n.number,n.series,formatDate(n.date),n.supplier,n.key,n.items.length,n.actor])};
 if(type==='movements')return {title:'Histórico de movimentações',headers:['Data','Tipo','Material','Categoria','Lote','Quantidade','Unidade','Referência','Observação','Responsável'],rows:state.movements.filter(m=>matches(m.date,[m.type,m.name,m.lot,m.reference,m.note].join(' '))).map(m=>[new Date(m.date).toLocaleString('pt-BR'),m.type,m.name,m.group,m.lot,m.quantity,m.unit,m.reference,m.note,m.actor])};
 const rows=[];state.acaps.filter(a=>matches(a.date,[a.id,a.activity,a.course,a.className,a.officer.nome].join(' '))).forEach(a=>a.items.forEach(i=>rows.push([a.id,formatDate(a.date),a.course,a.className,a.activity,a.officer.nome,a.status,i.name,i.lot,i.unit,i.delivered,i.consumed??'Pendente',i.returned??'Pendente',i.partial??'Pendente',i.failed??'Pendente',i.other??'Pendente',i.consumed==null?'Pendente':money(i.consumed*i.unitCost),i.note||''])));return {title:'Consumo e prestação de contas — ACAPS',headers:['Registro','Data','Curso','Turma','Atividade','Responsável','Situação','Material','Lote','Unidade','Entregue','Consumido / esgotado','Intacto devolvido','Uso parcial devolvido','Falha','Outras destinações','Custo consumido','Observação'],rows};
}
const REPORT_TYPES={stock:'Estoque de consumíveis',equipment:'Armas e equipamentos',loans:'Cautelas de policiais',acaps:'ACAPS — consumo',invoices:'Notas fiscais',movements:'Movimentações'};
views.reports=()=>{const report=reportData();const dated=!['stock','equipment'].includes(reportFilters.type);return heading('Relatórios','Salve em CSV ou HTML; imprima ou escolha “Salvar como PDF” na impressão.','<button class="btn ghost" id="saveCsv">Salvar CSV</button><button class="btn ghost" id="saveHtml">Salvar relatório</button><button class="btn primary" id="printReport">Imprimir / PDF</button>')+`<section class="panel"><form id="reportForm" class="report-filters"><label class="field">Relatório<select name="type" id="reportType">${Object.entries(REPORT_TYPES).map(([key,name])=>`<option value="${key}" ${key===reportFilters.type?'selected':''}>${name}</option>`).join('')}</select></label><label class="field">De<input type="date" name="from" value="${esc(reportFilters.from)}" ${dated?'':'disabled'}></label><label class="field">Até<input type="date" name="to" value="${esc(reportFilters.to)}" ${dated?'':'disabled'}></label><label class="field">Busca<input name="query" value="${esc(reportFilters.query)}" placeholder="Curso, policial, material..."></label><button class="btn primary">Aplicar</button></form><h2>${report.title}</h2><p class="muted">${report.rows.length} linha(s) · ${dated?'Período conforme filtro':'Posição atual do estoque'} · Dados locais de demonstração</p>${table(report.headers,report.rows.map(r=>r.map(esc)))}</section>`;};
views.backup=()=>heading('Dados e backup','Exporte todos os registros e restaure um backup produzido pelo próprio SIMB.')+`<section class="panel"><p class="unit-note">Ambiente de demonstração: dados neste navegador. Salve o backup antes de trocar de dispositivo ou limpar os dados.</p><div class="button-group"><button class="btn primary" id="exportBackup">Salvar backup JSON</button><label class="btn ghost">Importar backup<input type="file" id="importBackup" accept=".json,application/json" hidden></label></div><p id="backupStatus" role="status"></p></section>`;
function reportHtml(){const r=reportData();return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SIMB — ${esc(r.title)}</title><style>body{font:12px Arial;margin:24px;color:#18221b}h1{font-size:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #b9c2bb;padding:7px;text-align:left;overflow-wrap:anywhere}th{background:#edf1e7}thead{display:table-header-group}tr{break-inside:avoid}footer{margin-top:20px;font-size:10px}@page{size:A4 landscape;margin:12mm}</style><h1>SIMB · PPSC — ${esc(r.title)}</h1><p>Gerado em ${esc(new Date().toLocaleString('pt-BR'))} por MARCELO SEIXAS</p><p>Período: ${['stock','equipment'].includes(reportFilters.type)?'posição atual':`${esc(reportFilters.from||'início')} a ${esc(reportFilters.to||'hoje')}`} · Busca: ${esc(reportFilters.query||'todas')} · ${r.rows.length} linha(s)</p>${table(r.headers,r.rows.map(row=>row.map(esc)))}<footer>AMBIENTE DE DEMONSTRAÇÃO — contém dados fictícios. Sprays com uso parcial têm custo de consumo pendente de medição.</footer></html>`;}
function csvText(){const r=reportData();const cell=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return '\ufeff'+[r.headers,...r.rows].map(row=>row.map(cell).join(';')).join('\r\n');}
function printHtml(html){const frame=document.createElement('iframe');frame.className='print-frame';frame.title='Impressão do relatório';frame.srcdoc=html;frame.onload=()=>{frame.contentWindow.focus();frame.contentWindow.print();};document.body.appendChild(frame);setTimeout(()=>frame.remove(),120000);}
function modal(id,title,body){let d=document.querySelector('#'+id);if(!d){d=document.createElement('dialog');d.id=id;d.className='modal wide-modal';document.body.append(d);}d.innerHTML=`<div class="modal-card"><div class="modal-head"><div><p class="eyebrow">SIMB · PPSC</p><h2>${title}</h2></div><button type="button" class="icon-btn" aria-label="Fechar">×</button></div>${body}</div>`;d.querySelector('.modal-head button').onclick=()=>d.close();if(!d.open)d.showModal();return d;}
function stockForm(){const d=modal('stockDialog','Entrada de material',`<form id="stockForm"><div class="form-grid"><label>Material<input name="name" required maxlength="160"></label><label>Categoria<select name="group">${options(MATERIAL_GROUPS)}</select></label><label>Calibre / apresentação<input name="caliber"></label><label>Fabricante<input name="manufacturer" required></label><label>Modelo<input name="model"></label><label>Unidade<select name="unit">${options(['Unidade','Frasco'])}</select></label><label>Lote<input name="lot" required></label><label>Validade<input name="expiry" type="date"></label><label>Quantidade recebida<input name="balance" type="number" min="1" step="1" required></label><label>Valor por unidade (R$)<input name="unitCost" type="number" min="0" step="0.0001" value="0" required></label><label>Documento de entrada<input name="reference" required placeholder="NF, termo de transferência..."></label></div><div class="modal-actions"><button class="btn primary">Conferir e salvar entrada</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(mutate(()=>{const balance=amount(data.balance,'Quantidade',true);need(Number(data.unitCost)>=0,'Valor inválido.');const m={...data,id:uid('MAT'),balance,unitCost:Number(data.unitCost),unit:data.group==='Spray'?'Frasco':data.unit,partial:0,quarantine:0,demo:false};need(m.name.trim()&&m.lot.trim(),'Informe material e lote.');state.materials.push(m);movement('Entrada manual',m,balance,data.reference);addActivity(`Entrada registrada: ${m.name}`);})){d.close();render();showToast('Entrada salva no estoque.');}};}
function openAcaps(id){let a=id?state.acaps.find(a=>a.id===id):null;
 if(a&&a.status==='Encerrada'){const body=`<p><b>${esc(a.activity)}</b> · ${esc(a.course)} / ${esc(a.className)} · ${formatDate(a.date)}</p><p>${esc(a.officer.nome)} — POLICIAL PENAL · ${esc(a.officer.matricula)}</p>${table(['Material / lote','Entregue','Consumido','Intacto','Parcial','Falha','Outros','Observação'],a.items.map(i=>[`${esc(i.name)} / ${esc(i.lot)}`,i.delivered,i.consumed,i.returned,i.partial,i.failed,i.other,esc(i.note)]))}<div class="modal-actions"><button class="btn primary" id="printAcaps">Imprimir comprovante</button></div>`;const d=modal('acapsDialog','ACAPS',body);d.querySelector('#printAcaps').onclick=()=>{const old=reportFilters;reportFilters={type:'acaps',from:'',to:'',query:a.id};const html=reportHtml();reportFilters=old;printHtml(html);};return;}
 if(a){const d=modal('acapsDialog','ACAPS',`<p><b>Prestação de contas: ${esc(a.activity)}</b> · ${esc(a.officer.nome)}</p><p class="unit-note">Entregue = consumido/esgotado + intacto + uso parcial + falha + outras destinações. Registre justificativa para falhas e outras destinações.</p><form id="settleForm">${a.items.map((i,k)=>`<fieldset class="entry-row"><legend>${esc(i.name)} · lote ${esc(i.lot)} · ${i.delivered} ${esc(i.unit)} entregue(s)</legend><div class="form-grid">${[['consumed','Consumido / frascos esgotados'],['returned','Devolvido intacto'],...(i.group==='Spray'?[['partial','Frascos devolvidos com uso parcial']]:[]),['failed','Falha / segregado'],['other','Outras destinações']].map(([name,label])=>`<label>${label}<input type="number" name="${name}-${k}" min="0" max="${i.delivered}" step="1" value="0" required></label>`).join('')}<label>Justificativa / observação<input name="note-${k}"></label></div></fieldset>`).join('')}<div class="modal-actions"><button class="btn primary">Conferir e encerrar atividade</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(mutate(()=>{a=state.acaps.find(record=>record.id===id);need(a&&a.status==='Aberta','Atividade já encerrada.');const settlements=a.items.map((i,k)=>{const s={};for(const field of ['consumed','returned','partial','failed','other'])s[field]=amount(data[`${field}-${k}`]||0,field);s.note=(data[`note-${k}`]||'').trim();need(Object.values(s).filter(v=>typeof v==='number').reduce((x,y)=>x+y,0)===i.delivered,`Confira as quantidades de ${i.name}.`);need(!(s.failed||s.other)||s.note,`Justifique as ocorrências de ${i.name}.`);need(materialById(i.materialId),'Material não localizado.');return s;});a.items.forEach((i,k)=>{const s=settlements[k],m=materialById(i.materialId);Object.assign(i,s);m.balance+=s.returned;m.partial+=s.partial;m.quarantine+=s.failed;for(const [field,label] of [['consumed','Consumo ACAPS'],['returned','Devolução intacta'],['partial','Devolução uso parcial'],['failed','Falha / segregação'],['other','Outra destinação']])if(s[field])movement(label,m,s[field],a.id,s.note);});a.status='Encerrada';a.closed=stamp();a.checkedBy='MARCELO SEIXAS';addActivity(`ACAPS encerrada: ${a.activity}`);})){d.close();render();showToast('Consumo e devoluções registrados.');}};return;}
 const available=state.materials.filter(m=>m.balance>0&&(!m.expiry||m.expiry>=today()));const d=modal('acapsDialog','ACAPS',`<form id="acapsForm"><div class="form-grid"><label>Atividade<input name="activity" required></label><label>Curso<input name="course" required></label><label>Turma<input name="className" required></label><label>Disciplina<input name="discipline" required></label><label>Data<input name="date" type="date" value="${today()}" required></label><label>Local<input name="location" required></label><label>Responsável — matrícula<select name="officer">${officers.filter(o=>o.situacao==='Ativo').map(o=>`<option value="${o.matricula}">${esc(o.nome)} · ${o.matricula}</option>`).join('')}</select></label></div><h3>Materiais entregues</h3><p class="muted">Informe apenas as quantidades entregues. Lotes vencidos não aparecem para entrega.</p>${available.map(m=>`<label class="delivery-row"><span><b>${esc(m.name)}</b><small>Lote ${esc(m.lot)} · saldo ${m.balance} ${esc(m.unit)}${m.demo?' · FICTÍCIO':''}</small></span><input aria-label="Quantidade de ${esc(m.name)}" name="qty-${m.id}" type="number" min="0" max="${m.balance}" step="1" value="0"></label>`).join('')||'<p>Nenhum material disponível.</p>'}<h3>Armas e equipamentos vinculados</h3><p class="muted">Os itens selecionados gerarão uma cautela para o responsável, com devolução no módulo Devoluções.</p><div class="equipment-checks">${state.equipment.filter(e=>e.status==='Disponível').map(e=>`<label><input type="checkbox" name="equipment" value="${esc(e.patrimonio)}"> ${esc(e.patrimonio)} — ${esc(e.fabricante)} ${esc(e.modelo)}</label>`).join('')}</div><div class="modal-actions"><button class="btn primary">Registrar entrega</button></div></form>`);
 d.querySelector('form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target),data=Object.fromEntries(form);if(mutate(()=>{const officer=officerByMatricula(data.officer);need(officer&&officer.situacao==='Ativo','Responsável inválido.');const items=available.map(original=>{const m=materialById(original.id);need(m,'Material não localizado.');return {m,q:amount(data[`qty-${m.id}`]||0,m.name)};}).filter(x=>x.q>0);const equipment=form.getAll('equipment');need(items.length||equipment.length,'Selecione materiais ou equipamentos.');items.forEach(({m,q})=>{need(q<=m.balance,`Saldo insuficiente: ${m.name}`);need(!m.expiry||m.expiry>=today(),`Lote vencido: ${m.name}`);});equipment.forEach(id=>need(equipmentById(id)?.status==='Disponível','Equipamento indisponível.'));const record={id:`ACAPS-${String(state.acaps.length+1).padStart(6,'0')}`,activity:data.activity.trim(),course:data.course.trim(),className:data.className.trim(),discipline:data.discipline.trim(),date:data.date,location:data.location.trim(),officer:{...officer},created:stamp(),status:'Aberta',items:items.map(({m,q})=>({materialId:m.id,name:m.name,group:m.group,lot:m.lot,unit:m.unit,unitCost:m.unitCost,delivered:q})),equipment};need(record.activity&&record.course&&record.className,'Informe os dados da atividade.');items.forEach(({m,q})=>{m.balance-=q;movement('Entrega ACAPS',m,q,record.id);});if(equipment.length){const loanId=`CT-${String(Math.max(0,...state.loans.map(l=>Number(l.id.replace(/\D/g,''))))+1).padStart(6,'0')}`;state.loans.push({id:loanId,matricula:officer.matricula,officerSnapshot:{...officer},type:'Temporária',purpose:`ACAPS: ${record.activity} / ${record.course} / ${record.className}`,due:'',created:stamp(),status:'Ativa',items:equipment.map(patrimonio=>({patrimonio,returned:false,condition:''})),acapsId:record.id});equipment.forEach(id=>equipmentById(id).status='Cautelada');record.loanId=loanId;}state.acaps.push(record);addActivity(`Entrega ACAPS: ${record.activity}`);})){d.close();render();showToast('Entrega registrada. Confira ao término da atividade.');}};
}
function xmlNodes(node,name){return Array.from(node.getElementsByTagName('*')).filter(element=>element.localName===name);}
function xmlValue(node,name){return xmlNodes(node,name)[0]?.textContent.trim()||'';}
function parseInvoiceXml(text){need(!/<!DOCTYPE|<!ENTITY/i.test(text),'XML com declaração externa não é aceito.');const doc=new DOMParser().parseFromString(text,'application/xml');need(!doc.getElementsByTagName('parsererror').length,'XML inválido.');const inf=xmlNodes(doc,'infNFe')[0];need(inf,'Arquivo não contém uma NF-e.');const key=(inf.getAttribute('Id')||'').replace(/^NFe/,'');need(/^\d{44}$/.test(key),'Chave de NF-e inválida.');const emit=xmlNodes(inf,'emit')[0],ide=xmlNodes(inf,'ide')[0];need(emit&&ide,'Cabeçalho da nota incompleto.');const items=xmlNodes(inf,'det').map(det=>{const prod=xmlNodes(det,'prod')[0];need(prod,'Item sem produto.');const traces=xmlNodes(prod,'rastro');const lots=traces.length?traces:[null];return lots.map(trace=>({name:xmlValue(prod,'xProd'),code:xmlValue(prod,'cProd'),invoiceUnit:xmlValue(prod,'uCom'),invoiceQuantity:Number(xmlValue(prod,'qCom')),quantity:Number(trace?xmlValue(trace,'qLote'):xmlValue(prod,'qCom')),unitCost:Number(xmlValue(prod,'vUnCom')),lot:trace?xmlValue(trace,'nLote'):'',expiry:trace?xmlValue(trace,'dVal'):'',group:'',caliber:'',model:xmlValue(prod,'xProd'),manufacturer:xmlValue(emit,'xNome')}));}).flat();need(items.length,'NF-e sem itens.');need(items.every(i=>i.name&&Number.isFinite(i.quantity)&&i.quantity>0&&Number.isFinite(i.unitCost)&&i.unitCost>=0),'Quantidades ou valores inválidos no XML.');return {key,number:xmlValue(ide,'nNF'),series:xmlValue(ide,'serie'),date:(xmlValue(ide,'dhEmi')||xmlValue(ide,'dEmi')).slice(0,10),supplier:xmlValue(emit,'xNome'),cnpj:xmlValue(emit,'CNPJ'),items,origin:'XML',originalXml:text};}
function openInvoice(){invoiceDraft=null;const d=modal('invoiceDialog','Recebimento de nota fiscal',`<p class="unit-note">O XML é lido automaticamente. Confira classificação, lote, quantidade física e valor por unidade antes de salvar. A leitura não verifica autorização ou assinatura na SEFAZ.</p><label class="field">Selecionar XML da NF-e<input type="file" id="invoiceFile" accept=".xml,text/xml,application/xml"></label><p id="invoiceError" class="form-error" role="alert"></p><div class="modal-actions"><button class="btn ghost" id="manualInvoice">Conferência manual de PDF / imagem</button></div><div id="invoiceReview"></div>`);d.querySelector('#invoiceFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;need(f.size<=5*1024*1024,'XML excede 5 MB.');invoiceDraft=parseInvoiceXml(await f.text());need(!state.invoices.some(n=>n.key===invoiceDraft.key),'Esta nota já foi recebida.');d.querySelector('#invoiceError').textContent='';renderInvoiceReview(d);}catch(error){invoiceDraft=null;d.querySelector('#invoiceReview').innerHTML='';d.querySelector('#invoiceError').textContent=error.message;}};d.querySelector('#manualInvoice').onclick=()=>{invoiceDraft={key:'',number:'',series:'',date:today(),supplier:'',items:[],origin:'Manual'};renderInvoiceReview(d);};}
function invoiceItemForm(i,k){return `<fieldset class="entry-row" data-invoice-row="${k}"><legend>Item ${k+1}: ${esc(i.name||'novo material')}</legend><p class="muted">${i.invoiceUnit?`XML: ${i.invoiceQuantity} ${esc(i.invoiceUnit)} — confira conversão para unidades físicas.`:''}</p><div class="form-grid"><label>Descrição<input name="name-${k}" value="${esc(i.name)}" required></label><label>Natureza<select name="kind-${k}" data-kind="${k}"><option>Consumível</option><option>Equipamento</option></select></label><label>Categoria<select name="group-${k}" required><option value="">Selecione após conferir</option>${options([...MATERIAL_GROUPS,'Pistola','Fuzil','Carabina','Espingarda','Dispositivo elétrico','Equipamento'])}</select></label><label>Fabricante<input name="manufacturer-${k}" value="${esc(i.manufacturer||'')}" required></label><label>Modelo<input name="model-${k}" value="${esc(i.model||'')}"></label><label>Calibre / apresentação<input name="caliber-${k}"></label><label>Lote (consumível)<input name="lot-${k}" value="${esc(i.lot||'')}"></label><label>Validade<input name="expiry-${k}" type="date" value="${esc(i.expiry||'')}"></label><label>Quantidade física em unidades<input name="quantity-${k}" type="number" min="1" step="1" value="${i.quantity||1}" required></label><label>Unidade de controle<select name="unit-${k}">${options(['Unidade','Frasco'])}</select></label><label>Valor por unidade física (R$)<input name="unitCost-${k}" type="number" min="0" step="0.0001" value="${i.unitCost||0}" required></label><label>Patrimônios (equipamentos; um por linha)<textarea name="assets-${k}" placeholder="SIMB-ARM-0030"></textarea></label><label>Números de série (mesma ordem dos patrimônios)<textarea name="serials-${k}" placeholder="Série individual de cada equipamento"></textarea></label></div></fieldset>`;}
function renderInvoiceReview(d){const n=invoiceDraft;d.querySelector('#invoiceReview').innerHTML=`<form id="invoiceForm"><div class="form-grid"><label>Chave de acesso (44 dígitos)<input name="key" value="${esc(n.key)}" pattern="[0-9]{44}" required ${n.origin==='XML'?'readonly':''}></label><label>Número<input name="number" value="${esc(n.number)}" required></label><label>Série<input name="series" value="${esc(n.series)}" required></label><label>Emissão<input name="date" type="date" value="${esc(n.date)}" required></label><label>Fornecedor<input name="supplier" value="${esc(n.supplier)}" required></label>${n.origin==='Manual'?'<label>Consultar PDF / imagem<input id="referenceFile" type="file" accept="application/pdf,image/*"></label>':''}</div><div id="referencePreview"></div><div id="invoiceItems">${n.items.map(invoiceItemForm).join('')}</div>${n.origin==='Manual'?'<button type="button" class="btn ghost" id="addInvoiceItem">＋ Adicionar item</button>':''}<label class="check-note"><input type="checkbox" required> Conferi a nota, as quantidades físicas, lotes e valores unitários.</label><div class="modal-actions"><button class="btn primary">Salvar nota e registrar entrada</button></div></form>`;
 d.querySelector('#addInvoiceItem')?.addEventListener('click',()=>{const k=n.items.length;n.items.push({name:'',quantity:1,unitCost:0});d.querySelector('#invoiceItems').insertAdjacentHTML('beforeend',invoiceItemForm(n.items[k],k));});
 let referenceUrl=null;d.addEventListener('close',()=>{if(referenceUrl)URL.revokeObjectURL(referenceUrl);},{once:true});d.querySelector('#referenceFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(referenceUrl)URL.revokeObjectURL(referenceUrl);referenceUrl=URL.createObjectURL(f);n.referenceName=f.name;const p=d.querySelector('#referencePreview');p.replaceChildren();if(f.type.startsWith('image/')){const img=document.createElement('img');img.src=referenceUrl;img.alt='Nota fiscal para conferência';img.className='invoice-image';p.append(img);}else{const link=document.createElement('a');link.href=referenceUrl;link.target='_blank';link.rel='noopener';link.textContent='Abrir PDF para conferência';p.append(link);}const hint=document.createElement('p');hint.className='muted';hint.textContent='Documento aberto para consulta. O backup guarda os dados conferidos e o nome do arquivo; preserve o original separadamente.';p.append(hint);});
 d.querySelector('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(mutate(()=>{need(/^\d{44}$/.test(data.key),'Informe a chave de acesso de 44 dígitos.');need(!state.invoices.some(x=>x.key===data.key),'Esta nota já foi recebida.');need(n.items.length,'Inclua pelo menos um item.');const allAssets=new Set(state.equipment.map(e=>e.patrimonio.toUpperCase())),allSerials=new Set(state.equipment.map(e=>e.serie.toUpperCase()));const items=n.items.map((item,k)=>{const get=name=>(data[`${name}-${k}`]||'').trim();const kind=get('kind'),group=get('group'),quantity=amount(get('quantity'),'Quantidade',true),unitCost=Number(get('unitCost'));need(get('name')&&get('manufacturer')&&group,'Preencha a identificação dos itens.');need(Number.isFinite(unitCost)&&unitCost>=0,'Valor unitário inválido.');let equipment=[];if(kind==='Consumível'){need(MATERIAL_GROUPS.includes(group),'Selecione uma categoria de consumível.');need(get('lot'),'Informe o lote do consumível.');}else{need(!MATERIAL_GROUPS.includes(group),'Selecione a categoria do equipamento.');const assets=get('assets').split(/\n/).map(s=>s.trim().toUpperCase()).filter(Boolean),serials=get('serials').split(/\n/).map(s=>s.trim()).filter(Boolean);need(assets.length===quantity&&serials.length===quantity,'Informe um patrimônio e uma série para cada equipamento.');equipment=assets.map((asset,j)=>{need(!allAssets.has(asset),'Patrimônio duplicado: '+asset);need(!allSerials.has(serials[j].toUpperCase()),'Série duplicada: '+serials[j]);allAssets.add(asset);allSerials.add(serials[j].toUpperCase());return {patrimonio:asset,serie:serials[j],categoria:group,fabricante:get('manufacturer'),modelo:get('model')||get('name'),calibre:get('caliber')||'Não se aplica',status:'Disponível',unidade:'PPSC',invoiceKey:data.key};});}return {name:get('name'),group,quantity,unitCost,kind,lot:get('lot'),expiry:get('expiry'),manufacturer:get('manufacturer'),model:get('model'),caliber:get('caliber'),unit:group==='Spray'?'Frasco':get('unit'),equipment};});const record={...n,key:data.key,number:data.number.trim(),series:data.series.trim(),date:data.date,supplier:data.supplier.trim(),items,created:stamp(),actor:'MARCELO SEIXAS'};items.forEach(i=>{if(i.kind==='Equipamento'){state.equipment.push(...i.equipment);}else{const m={id:uid('MAT'),name:i.name,group:i.group,manufacturer:i.manufacturer,model:i.model,caliber:i.caliber,lot:i.lot,expiry:i.expiry,unit:i.unit,unitCost:i.unitCost,balance:i.quantity,partial:0,quarantine:0,invoiceKey:record.key,demo:false};state.materials.push(m);movement('Entrada por NF',m,i.quantity,record.key);}});state.invoices.push(record);addActivity(`NF ${record.number} recebida: ${record.supplier}`);})){d.close();invoiceDraft=null;render();showToast('Nota conferida e entrada registrada.');}};
}
function validBackup(s){need(s&&typeof s==='object','Backup inválido.');for(const key of ['equipment','loans','activities','materials','acaps','invoices','movements'])need(Array.isArray(s[key]),`Backup sem ${key}.`);need(s.equipment.every(e=>e&&typeof e.patrimonio==='string'&&typeof e.serie==='string'&&typeof e.status==='string'),'Equipamentos inválidos.');need(new Set(s.equipment.map(e=>e.patrimonio)).size===s.equipment.length,'Patrimônios duplicados.');need(s.loans.every(l=>l&&typeof l.id==='string'&&l.officerSnapshot&&typeof l.officerSnapshot.nome==='string'&&Array.isArray(l.items)&&l.items.every(i=>s.equipment.some(e=>e.patrimonio===i.patrimonio))),'Cautelas inválidas.');need(s.materials.every(m=>m&&typeof m.name==='string'&&typeof m.id==='string'&&typeof m.lot==='string'&&typeof m.unit==='string'&&[m.balance,m.partial,m.quarantine].every(v=>Number.isSafeInteger(v)&&v>=0)&&Number.isFinite(m.unitCost)&&m.unitCost>=0),'Materiais inválidos.');need(new Set(s.materials.map(m=>m.id)).size===s.materials.length,'Materiais duplicados.');need(s.acaps.every(a=>a&&typeof a.id==='string'&&['Aberta','Encerrada'].includes(a.status)&&a.officer&&typeof a.officer.nome==='string'&&Array.isArray(a.items)&&a.items.every(i=>s.materials.some(m=>m.id===i.materialId)&&Number.isSafeInteger(i.delivered)&&i.delivered>0&&(a.status==='Aberta'||(['consumed','returned','partial','failed','other'].every(k=>Number.isSafeInteger(i[k])&&i[k]>=0)&&['consumed','returned','partial','failed','other'].reduce((n,k)=>n+i[k],0)===i.delivered)))),'Atividades ACAPS inválidas.');need(s.invoices.every(n=>n&&/^\d{44}$/.test(n.key)&&Array.isArray(n.items)),'Notas inválidas.');need(new Set(s.invoices.map(n=>n.key)).size===s.invoices.length,'Notas duplicadas.');need(s.movements.every(m=>m&&typeof m.name==='string'&&typeof m.date==='string'&&Number.isSafeInteger(m.quantity)&&m.quantity>=0),'Movimentações inválidas.');return s;}
const baseBind=bindViewEvents;
bindViewEvents=function(){baseBind();document.querySelectorAll('[data-print-loan]').forEach(b=>b.onclick=()=>printLoan(b.dataset.printLoan));document.querySelector('#newMaterial')?.addEventListener('click',stockForm);document.querySelector('#materialSearch')?.addEventListener('input',e=>{materialQuery=e.target.value;const start=e.target.selectionStart;render();const input=document.querySelector('#materialSearch');input.focus();input.setSelectionRange(start,start);});document.querySelector('#newAcaps')?.addEventListener('click',()=>openAcaps());document.querySelectorAll('[data-acaps]').forEach(b=>b.onclick=()=>openAcaps(b.dataset.acaps));document.querySelector('#openInvoice')?.addEventListener('click',openInvoice);document.querySelector('#reportType')?.addEventListener('change',e=>{reportFilters.type=e.target.value;if(['stock','equipment'].includes(reportFilters.type)){reportFilters.from='';reportFilters.to='';}render();});document.querySelector('#reportForm')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(data.from&&data.to&&data.from>data.to)return showToast('A data inicial deve ser anterior à final.');reportFilters={type:data.type,from:data.from||'',to:data.to||'',query:(data.query||'').trim()};render();});document.querySelector('#saveCsv')?.addEventListener('click',()=>download(`SIMB-${reportFilters.type}-${today()}.csv`,csvText(),'text/csv;charset=utf-8'));document.querySelector('#saveHtml')?.addEventListener('click',()=>download(`SIMB-${reportFilters.type}-${today()}.html`,reportHtml(),'text/html;charset=utf-8'));document.querySelector('#printReport')?.addEventListener('click',()=>printHtml(reportHtml()));document.querySelector('#exportBackup')?.addEventListener('click',()=>download(`SIMB-backup-${today()}.json`,JSON.stringify({format:'SIMB',version:2,exportedAt:stamp(),state},null,2),'application/json'));document.querySelector('#importBackup')?.addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;need(f.size<=20*1024*1024,'Backup excede 20 MB.');const json=JSON.parse(await f.text());need(json.format==='SIMB'&&json.version===2,'Use um backup JSON gerado por esta versão do SIMB.');const restored=validBackup(json.state);if(!confirm('Substituir os dados locais pelo backup? Exporte os dados atuais antes de continuar.'))return;if(mutate(()=>{state=restored;state.loans.forEach(l=>l.officerSnapshot.graduacao='POLICIAL PENAL');state.acaps.forEach(a=>a.officer.graduacao='POLICIAL PENAL');draft={officer:null,items:[]};ensureModules();})){render();document.querySelector('#backupStatus').textContent='Backup restaurado com sucesso.';}}catch(error){showToast(error.message||'Backup inválido.');}});};
const baseRender=render;
render=function(){ensureModules();baseRender();const titles={materials:'Estoque de consumíveis',acaps:'ACAPS',invoices:'Notas fiscais',reports:'Relatórios',backup:'Dados e backup'};if(titles[currentView])document.querySelector('#pageTitle').textContent=titles[currentView];};
document.querySelector('#resetBtn').onclick=()=>{if(confirm('Restaurar todos os dados fictícios? As alterações locais serão perdidas.')){if(mutate(()=>{state=initialState();ensureModules();draft={officer:null,items:[]};})){render();showToast('Dados fictícios restaurados.');}}};
if(sessionStorage.getItem(SESSION_KEY))render();

function printLoan(id){const loan=state.loans.find(l=>l.id===id);if(!loan)return;const rows=loan.items.map(i=>{const e=equipmentById(i.patrimonio);return [i.patrimonio,e?.fabricante||'',e?.modelo||'',e?.calibre||'',e?.serie||'',i.returned?'Devolvido':'Pendente',i.condition||''];});const body=`<h1>SIMB · PPSC — Termo de cautela ${esc(loan.id)}</h1><p>Policial penal: <b>${esc(loan.officerSnapshot.nome)}</b> · Matrícula ${esc(loan.matricula)}</p><p>Emissão: ${formatDate(loan.created)} · Tipo: ${esc(loan.type)} · Previsão de devolução: ${formatDate(loan.due)}</p><p>Finalidade: ${esc(loan.purpose)}</p><p>Observações: ${esc(loan.notes||'—')}</p>${table(['Patrimônio','Fabricante','Modelo','Calibre','Série','Situação','Condição'],rows.map(r=>r.map(esc)))}<p style="margin-top:60px">____________________________________ &nbsp; ____________________________________</p><p>Policial penal responsável &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Responsável pela entrega / conferência</p><p>AMBIENTE DE DEMONSTRAÇÃO — dados fictícios</p>`;printHtml(`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Cautela ${esc(id)}</title><style>body{font:12px Arial;margin:30px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #aaa;padding:8px}h1{font-size:20px}@page{size:A4;margin:15mm}</style>${body}</html>`);}
